-- MySQL Script generated by MySQL Workbench
-- Ter 20 Jun 2017 11:39:21 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema testserver
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `testserver` ;

-- -----------------------------------------------------
-- Schema testserver
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testserver` DEFAULT CHARACTER SET utf8 ;
USE `testserver` ;

-- -----------------------------------------------------
-- Table `testserver`.`Equipamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testserver`.`Equipamentos` ;

CREATE TABLE IF NOT EXISTS `testserver`.`Equipamentos` (
  `idEquipamento` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEquipamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testserver`.`Testes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testserver`.`Testes` ;

CREATE TABLE IF NOT EXISTS `testserver`.`Testes` (
  `idTeste` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  `timestamp` VARCHAR(45) NOT NULL,
  `idEquipamento` INT NOT NULL,
  PRIMARY KEY (`idTeste`),
  INDEX `fk_Testes_Equipamentos_idx` (`idEquipamento` ASC),
  CONSTRAINT `fk_Testes_Equipamentos`
    FOREIGN KEY (`idEquipamento`)
    REFERENCES `testserver`.`Equipamentos` (`idEquipamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testserver`.`LogFalhas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testserver`.`LogFalhas` ;

CREATE TABLE IF NOT EXISTS `testserver`.`LogFalhas` (
  `idLogFalha` INT NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `idTeste` INT NOT NULL,
  PRIMARY KEY (`idLogFalha`),
  INDEX `fk_LogFalhas_Testes1_idx` (`idTeste` ASC),
  CONSTRAINT `fk_LogFalhas_Testes1`
    FOREIGN KEY (`idTeste`)
    REFERENCES `testserver`.`Testes` (`idTeste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
