-- MySQL Script generated by MySQL Workbench
-- Fri Aug  4 13:47:32 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema testserverdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `testserverdb` ;

-- -----------------------------------------------------
-- Schema testserverdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testserverdb` DEFAULT CHARACTER SET utf8 ;
USE `testserverdb` ;

-- -----------------------------------------------------
-- Table `testserverdb`.`Hradc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testserverdb`.`Hradc` ;

CREATE TABLE IF NOT EXISTS `testserverdb`.`Hradc` (
  `numero_serie` BIGINT(15) NOT NULL,
  `variante` VARCHAR(45) NULL,
  `data_instalacao` DATETIME NULL,
  `nome_operador` VARCHAR(120) NULL,
  `resistor_burden` DOUBLE NULL,
  `frequencia_corte` DOUBLE NULL,
  `ordem_filtro` INT NULL,
  `controlador_temperatura` INT NULL,
  `amplificador_burden` VARCHAR(45) NULL,
  `jumper_gnd` TINYINT NULL,
  `jumper_burden` TINYINT NULL,
  `filtro_modo_comum` TINYINT NULL,
  PRIMARY KEY (`numero_serie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testserverdb`.`Udc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testserverdb`.`Udc` ;

CREATE TABLE IF NOT EXISTS `testserverdb`.`Udc` (
  `numero_serie` BIGINT(15) NOT NULL,
  PRIMARY KEY (`numero_serie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testserverdb`.`ModuloPotencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testserverdb`.`ModuloPotencia` ;

CREATE TABLE IF NOT EXISTS `testserverdb`.`ModuloPotencia` (
  `numero_serie` BIGINT(15) NOT NULL,
  PRIMARY KEY (`numero_serie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testserverdb`.`Bastidor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testserverdb`.`Bastidor` ;

CREATE TABLE IF NOT EXISTS `testserverdb`.`Bastidor` (
  `numero_serie` BIGINT(15) NOT NULL,
  PRIMARY KEY (`numero_serie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testserverdb`.`Fonte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testserverdb`.`Fonte` ;

CREATE TABLE IF NOT EXISTS `testserverdb`.`Fonte` (
  `numero_serie` BIGINT(15) NOT NULL,
  PRIMARY KEY (`numero_serie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testserverdb`.`LogBastidor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testserverdb`.`LogBastidor` ;

CREATE TABLE IF NOT EXISTS `testserverdb`.`LogBastidor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `resultado_teste` VARCHAR(45) NOT NULL,
  `numero_serie_bastidor` BIGINT(15) NOT NULL,
  `iout0` DOUBLE NULL,
  `iout1` DOUBLE NULL,
  `iout2` DOUBLE NULL,
  `iout3` DOUBLE NULL,
  `delta_iout0` DOUBLE NULL,
  `delta_iout1` DOUBLE NULL,
  `delta_iout2` DOUBLE NULL,
  `delta_iout3` DOUBLE NULL,
  `details` TEXT(500) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LogBastidor_Bastidor1_idx` (`numero_serie_bastidor` ASC),
  CONSTRAINT `fk_LogBastidor_Bastidor1`
    FOREIGN KEY (`numero_serie_bastidor`)
    REFERENCES `testserverdb`.`Bastidor` (`numero_serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testserverdb`.`CanalFonte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testserverdb`.`CanalFonte` ;

CREATE TABLE IF NOT EXISTS `testserverdb`.`CanalFonte` (
  `id` INT NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testserverdb`.`LogFonte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testserverdb`.`LogFonte` ;

CREATE TABLE IF NOT EXISTS `testserverdb`.`LogFonte` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `resultado_teste` VARCHAR(45) NOT NULL,
  `numero_serie_fonte` BIGINT(15) NOT NULL,
  `id_canal_fonte` INT NOT NULL,
  `resultado_teste_on_off` VARCHAR(45) NULL,
  `iout_mais_20_duty_cycle` DOUBLE NULL,
  `iout_menos_20_duty_cycle` DOUBLE NULL,
  `iout0` DOUBLE NULL,
  `iout1` DOUBLE NULL,
  `vout0` DOUBLE NULL,
  `vout1` DOUBLE NULL,
  `vdclink0` DOUBLE NULL,
  `vdclink1` DOUBLE NULL,
  `temperatura0` DOUBLE NULL,
  `temperatura1` DOUBLE NULL,
  `details` TEXT(500) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LogFonte_Fonte1_idx` (`numero_serie_fonte` ASC),
  INDEX `fk_LogFonte_CanalFonte1_idx` (`id_canal_fonte` ASC),
  CONSTRAINT `fk_LogFonte_Fonte1`
    FOREIGN KEY (`numero_serie_fonte`)
    REFERENCES `testserverdb`.`Fonte` (`numero_serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LogFonte_CanalFonte1`
    FOREIGN KEY (`id_canal_fonte`)
    REFERENCES `testserverdb`.`CanalFonte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testserverdb`.`Medida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testserverdb`.`Medida` ;

CREATE TABLE IF NOT EXISTS `testserverdb`.`Medida` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testserverdb`.`LogHradc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testserverdb`.`LogHradc` ;

CREATE TABLE IF NOT EXISTS `testserverdb`.`LogHradc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `resultado_teste` VARCHAR(45) NULL,
  `numero_serie_hradc` BIGINT(15) NOT NULL,
  `details` TEXT(500) NULL,
  `gnd` DOUBLE NULL,
  `vref_p` DOUBLE NULL,
  `vref_n` DOUBLE NULL,
  `temperatura` DOUBLE NULL,
  `vin_p` DOUBLE NULL,
  `vin_n` DOUBLE NULL,
  `lin_p` DOUBLE NULL,
  `lin_n` DOUBLE NULL,
  `id_medida` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LogHradc_Hradc_idx` (`numero_serie_hradc` ASC),
  INDEX `fk_LogHradc_Medida1_idx` (`id_medida` ASC),
  CONSTRAINT `fk_LogHradc_Hradc`
    FOREIGN KEY (`numero_serie_hradc`)
    REFERENCES `testserverdb`.`Hradc` (`numero_serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LogHradc_Medida1`
    FOREIGN KEY (`id_medida`)
    REFERENCES `testserverdb`.`Medida` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testserverdb`.`LogModuloPotencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testserverdb`.`LogModuloPotencia` ;

CREATE TABLE IF NOT EXISTS `testserverdb`.`LogModuloPotencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `resultado_teste` VARCHAR(45) NOT NULL,
  `numero_serie_modulo_potencia` BIGINT(15) NOT NULL,
  `iload0` DOUBLE NULL,
  `iload1` DOUBLE NULL,
  `iload2` DOUBLE NULL,
  `iload3` DOUBLE NULL,
  `iload4` DOUBLE NULL,
  `iload5` DOUBLE NULL,
  `vload0` DOUBLE NULL,
  `vload1` DOUBLE NULL,
  `vload2` DOUBLE NULL,
  `vload3` DOUBLE NULL,
  `vload4` DOUBLE NULL,
  `vload5` DOUBLE NULL,
  `vdclink0` DOUBLE NULL,
  `vdclink1` DOUBLE NULL,
  `vdclink2` DOUBLE NULL,
  `vdclink3` DOUBLE NULL,
  `vdclink4` DOUBLE NULL,
  `vdclink5` DOUBLE NULL,
  `temperatura0` DOUBLE NULL,
  `temperatura1` DOUBLE NULL,
  `temperatura2` DOUBLE NULL,
  `temperatura3` DOUBLE NULL,
  `temperatura4` DOUBLE NULL,
  `temperatura5` DOUBLE NULL,
  `details` TEXT(500) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LogModuloPotencia_ModuloPotencia1_idx` (`numero_serie_modulo_potencia` ASC),
  CONSTRAINT `fk_LogModuloPotencia_ModuloPotencia1`
    FOREIGN KEY (`numero_serie_modulo_potencia`)
    REFERENCES `testserverdb`.`ModuloPotencia` (`numero_serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testserverdb`.`LogUdc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testserverdb`.`LogUdc` ;

CREATE TABLE IF NOT EXISTS `testserverdb`.`LogUdc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `resultado_teste` VARCHAR(45) NOT NULL,
  `numero_serie_udc` BIGINT(15) NOT NULL,
  `io_expander0` VARCHAR(45) NULL,
  `io_expander1` VARCHAR(45) NULL,
  `leds` VARCHAR(45) NULL,
  `buzzer` VARCHAR(45) NULL,
  `eeprom` VARCHAR(45) NULL,
  `flash` VARCHAR(45) NULL,
  `ram` VARCHAR(45) NULL,
  `rtc_communication` VARCHAR(45) NULL,
  `rtc_interrupt` VARCHAR(45) NULL,
  `sensor_temperatura_com` VARCHAR(45) NULL,
  `sensor_temperatura_val` VARCHAR(45) NULL,
  `control_aliment_plano_isolado` VARCHAR(45) NULL,
  `rs4850` VARCHAR(45) NULL,
  `rs4851` VARCHAR(45) NULL,
  `rs4852` VARCHAR(45) NULL,
  `sdcard_inserido` VARCHAR(45) NULL,
  `sdcard_communication` VARCHAR(45) NULL,
  `ethernet_inicializacao` VARCHAR(45) NULL,
  `ethernet_ping` VARCHAR(45) NULL,
  `loopback` TEXT(5000) NULL,
  `details` TEXT(500) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LogUdc_Udc1_idx` (`numero_serie_udc` ASC),
  CONSTRAINT `fk_LogUdc_Udc1`
    FOREIGN KEY (`numero_serie_udc`)
    REFERENCES `testserverdb`.`Udc` (`numero_serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testserverdb`.`Dcct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testserverdb`.`Dcct` ;

CREATE TABLE IF NOT EXISTS `testserverdb`.`Dcct` (
  `numero_serie` BIGINT(15) NOT NULL,
  `variante` VARCHAR(45) NULL,
  PRIMARY KEY (`numero_serie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testserverdb`.`CanalDcct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testserverdb`.`CanalDcct` ;

CREATE TABLE IF NOT EXISTS `testserverdb`.`CanalDcct` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testserverdb`.`LogDcct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testserverdb`.`LogDcct` ;

CREATE TABLE IF NOT EXISTS `testserverdb`.`LogDcct` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `resultado_teste` VARCHAR(45) NOT NULL,
  `numero_serie_dcct` BIGINT(15) NOT NULL,
  `iload0` DOUBLE NULL,
  `iload1` DOUBLE NULL,
  `iload2` DOUBLE NULL,
  `iload3` DOUBLE NULL,
  `iload4` DOUBLE NULL,
  `iload5` DOUBLE NULL,
  `iload6` DOUBLE NULL,
  `iload7` DOUBLE NULL,
  `iload8` DOUBLE NULL,
  `iload9` DOUBLE NULL,
  `iload10` DOUBLE NULL,
  `details` TEXT(500) NULL,
  `id_canal_dcct` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LogDcct_Dcct1_idx` (`numero_serie_dcct` ASC),
  INDEX `fk_LogDcct_CanalDcct1_idx` (`id_canal_dcct` ASC),
  CONSTRAINT `fk_LogDcct_Dcct1`
    FOREIGN KEY (`numero_serie_dcct`)
    REFERENCES `testserverdb`.`Dcct` (`numero_serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LogDcct_CanalDcct1`
    FOREIGN KEY (`id_canal_dcct`)
    REFERENCES `testserverdb`.`CanalDcct` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testserverdb`.`CalibHradc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testserverdb`.`CalibHradc` ;

CREATE TABLE IF NOT EXISTS `testserverdb`.`CalibHradc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NULL,
  `temperatura_hradc` DOUBLE NULL,
  `temperatura_dmm` DOUBLE NULL,
  `temperatura_fonte` DOUBLE NULL,
  `nome_operador` VARCHAR(120) NULL,
  `ganho_vin` DOUBLE NULL,
  `offset_vin` DOUBLE NULL,
  `ganho_lin` DOUBLE NULL,
  `offset_lin` DOUBLE NULL,
  `vref_p` DOUBLE NULL,
  `vref_n` DOUBLE NULL,
  `gnd` DOUBLE NULL,
  `numero_serie_hradc` BIGINT(15) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CalibHradc_Hradc1_idx` (`numero_serie_hradc` ASC),
  CONSTRAINT `fk_CalibHradc_Hradc1`
    FOREIGN KEY (`numero_serie_hradc`)
    REFERENCES `testserverdb`.`Hradc` (`numero_serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
